### ISSUE TITLE
Create release versions

### ISSUE THREAD

**Issue by BrunoS3D** [jpedroschmitz/typescript-nextjs-starter#199]
I use this template a lot, used multiple versions of it.
I believe you could create release tags for every major update you make to it.

**Comment by jpedroschmitz** [comment]
Hey @BrunoS3D! Wow, that's super nice =D

Believe it or not, I was thinking this week about adding releases when I addressed some changes to support Next.js 11.

I'll definitely create a changelog or release tags on updates.

**Comment by jpedroschmitz** [comment]
Hey @BrunoS3D, I've shipped some updates to the starter and released the [first official version](https://github.com/jpedroschmitz/typescript-nextjs-starter/releases/tag/1.0.0), although the starter is already being used for almost 2 years ❤️ 

I'll post all updates as releases since it's better than changelogs. Let me know what you think 🚀

I'll close this issue. Thanks a lot!

**Comment by BrunoS3D** [comment]
Your template has helped me a lot by accelerating the creation of projects that we carry out almost monthly and this update will be very important for us to have access to stable versions while the project is updated. 
I wish you good luck and that it has more adoption from the developer community Next.js. ❤️🚀🇧🇷
